mozilla-releng/OpenCloudConfig

userdata/Manifest/win2012.json
userdata/UserConfig.ps1
userdata/win2012.ps1

Hey @grenade,
I've mostly guessed what I need to do here, in order to update the version of the generic worker from `v2.0.0alpha25` to `v2.0.0alpha31`, and to run the install target (`generic-worker.exe install startup`).
I reverted commit e29a24624f0b80916ec9173ced9db1d33b9f6dff since I *think* that was mostly doing the same things that the new `install startup` steps are doing, e.g.:
* [`install(...)`](https://github.com/taskcluster/generic-worker/blob/v2.0.0alpha31/plat_windows.go#L380-L418)
* [`deployStartup(...)`](https://github.com/taskcluster/generic-worker/blob/v2.0.0alpha31/plat_windows.go#L444-L489)
* [`createOSUserAccountForce(...)`](https://github.com/taskcluster/generic-worker/blob/v2.0.0alpha31/plat_windows.go#L106-L162)
In short, the only changes from how it used to be are: …

Install generic worker as a startup item

---

userdata/Manifest/win2012.json

This is the first official release of GW which I wanted to make now that it is stable, before we go live.
The changes that will get picked up are:
https://github.com/taskcluster/generic-worker/compare/v2.0.0alpha43...v2.0.0

Bug 1279260 - updated version of generic worker to 2.0.0

---

userdata/Manifest/win10.json
userdata/Manifest/win2012.json
userdata/Manifest/win7.json

This provides new features:
* One livelog instead of one per command, named same as docker-worker log file
* Worker type metadata now logged at start of log file
* Exit code of processes logged in log file
* Total task execution time logged in log file

Bumped version of generic worker to 5.0.0

---

ci/update-workertype.sh

@grenade Note, you'll probably need to update the worker type definitions first to point to some other AMI in `eu-central-1`, so that when `update_workertype.sh` runs, it has something to update with the new AMI in that region...
Note I dropped `aws_regions` as I couldn't see it being used somewhere - let me know if this is ok.

Added eu-central-1 region

---

userdata/Manifest/win10.json
userdata/Manifest/win2012.json
userdata/Manifest/win7.json

Note, I had to build gw on my mac, rather than in travis, due to gimme being broken in travis at the moment. Hope it works ok! One consequence is that it is built with go 1.6 instead of go 1.5.

Upgraded generic worker to version 5.0.1

---

userdata/Configuration/Mercurial/mercurial.us-east-1.ini
userdata/Configuration/Mercurial/mercurial.us-west-1.ini
userdata/Configuration/Mercurial/mercurial.us-west-2.ini

This is maybe a short/medium term fix - long term we probably want a way that fingerprint checking is either self-managing (if possible) or doesn't require new AMIs to be created when a fingerprint changes...
I'm pretty sure [bundleclone](https://www.mercurial-scm.org/wiki/BundleCloneExtension#Configuration) should be able to handle that automatically, as keys are signed by a CA, and [hg already handles such things](https://www.mercurial-scm.org/wiki/CACertificates).

Bug 1292399 - updated outdated fingerprints

---

userdata/Manifest/win10.json
userdata/Manifest/win2012.json
userdata/Manifest/win7.json

This picks up [bug 1291249](https://bugzilla.mozilla.org/show_bug.cgi?id=1291249) (gzipped log files).
See [changes to generic worker](https://github.com/taskcluster/generic-worker/compare/v5.0.1...v5.1.0).
The other commits just relate to getting travis making releases against since gimme tool broke.

Upgraded generic worker from version 5.0.1 to version 5.1.0 (gzipped log files)

---

userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/win10.json
userdata/Manifest/win7.json

@grenade This new release adds some debugging for the claim-expired bug, only. So no fixes, but hopefully better debug logs...
Thanks!

Upgraded win test worker types to use generic worker 6.0.5 (from 6.0.4). 

---

userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/win10.json
userdata/Manifest/win7.json

@grenade Hope this finally fixes the claim-expired issue!

Upgraded win test worker types from generic worker 6.0.5 -> 6.0.6

---

userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/win10.json
userdata/Manifest/win7.json

Initially, just updating test environments (Windows 7, Windows 10), and if all goes ok, we can upgrade builders (manifests for `gecko-{1,2,3}-b-win2012`, `win2012`) in a separate PR.

Bug 1303455 - Upgrade generic worker to v7.0.0 on win7 and win10 worker types

---

userdata/Configuration/SeAssignPrimaryTokenPrivilege-GW.secpol
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

@grenade 
The new worker has two changes:
1) it takes care of setting required privileges on install, so no need to do this in the userdata now (so removed those parts). I think the other `Carbon` entries are still needed because of bug 1316329 - but if not, those can also be removed.
2) the `runlib` library has been forked, and modified - hopefully this will solve bug 1303455 - but I won't get too excited quite yet.

Upgrade win7/win10 beta worker types to g-w 7.0.3alpha1

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Thanks @grenade!
Small [change](https://github.com/taskcluster/generic-worker/compare/v7.2.0...v7.2.1) only. :-)

Upgraded generic worker from 7.2.0 to 7.2.1 on beta worker types

---

userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

Thanks @grenade!
I'll keep a watchful eye out once this lands, to make sure all is still ok.

Bug 1328241 - upgrade generic worker to reduce worker crashes

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json

@grenade Since rolling out to win7, we've had no worker crashes, so I'd like to test this on the other worker types too, first on the "beta" variant. If testing goes well, we should be able to roll out globally. We'll probably still have some win2012 crashes, because those don't reboot between tasks (they don't have a custom `run-generic-worker.bat` script - we can evaluate later if it is better to reboot to avoid these blue jobs - or to leave as they are and accept the occasional blue job, but have less overhead per task.
Thanks!

Upgraded gecko-1-b-win2012-beta and gecko-t-win10-64-beta to generic-worker v7.2.5

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

For win7 and all beta worker type variants.
__Please don't merge until CET working hours so I can be around to support in case of fallout.__
Thanks @grenade!

Bug 1329617 - upgrade generic worker from 7.2.5 to 7.2.6

---

userdata/Manifest/gecko-t-win7-32.json

Exposing transfer-encoding CORS requests, so logviewer can detect that the log is live.

Bump livelog to version 1.0.1

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Finally solved the frequent blue jobs issue (at least the new CI suggests so). This initial PR is just to upgrade the beta worker types. If that goes well, we can look at upgrading the other worker types too.
Thanks @grenade!

Bug 1317671 - Upgrade all beta worker types to generic worker 7.3.0

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

@grenade Can you take a look? Thanks!

Bug 1337132 - Rolling back generic worker on 2012 machines from 8.0.0 to 7.1.3

---

.taskcluster.yml
ci/update-workertype.sh
userdata/Manifest/gecko-t-win10-64-cu.json

Exactly the same as `gecko-t-win10-64`. The only difference is:
* the worker type config, where `maxCapacity` is 1 and `runTasksAsCurrentUser` is `true`, and the secrets contain tc creds for running unit tests
* only privileged users and the generic worker github CI should be able to trigger jobs for this worker type

Created gecko-t-win10-64-cu

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-alpha.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-alpha.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

I'm trying to get Mercurial 4.1 deployed everywhere at Mozilla.
This is a precursor to me installing a hacked up version of 4.1 to test fixes for the "stream ended unexpectedly" failures that keep popping up in automation. But that's for another pull request. The important thing is we get 4.1 verified to be working.

Bug 1351513 - Mass update to Mercurial 4.1.1

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

@grenade This adds support for specifying an artifact name which is different to the artifact path (i.e. so you can name your artifacts independently from where they are on the filesystem).
Note, it is backwardly compatible, so if you don't specify an artifact name, the artifact path is used for the name, as before.

Upgrade generic worker to 8.1.0 in *beta* worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

@grenade 
This picks up the fixes in generic worker from bugs [1338464](https://bugzilla.mozilla.org/show_bug.cgi?id=1338464) and [1356800](https://bugzilla.mozilla.org/show_bug.cgi?id=1356800) and applies them to the __beta__ worker types only.
__Note__, release 8.2.0 is currently in progress, but __when the win32 and win64__ binaries appear [here](https://github.com/taskcluster/generic-worker/releases/tag/v8.2.0) this PR should be safe to merge.
CC @garndt

Upgrade generic-worker to version 8.2.0 in beta worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

@grenade A new day, a new release!
The [try push of 8.2.0](https://treeherder.mozilla.org/#/jobs?repo=try&revision=4c74a5a145740c8393f9f797c4c593ce4818b935) was successful. This builds on top of that with fixes for bug 1343582 and bug 1347956. Again, just for the __beta__ worker types.
These fixes hopefully solve the "black screen" issue we've been having on Windows 10, and also should use gzip content encoding on more artifacts, which should considerably reduce storage requirements.
CC @gregarndt @edmorley

Bug 1343582, Bug 1347956 - upgrade generic-worker to 8.3.0 on beta worker types

---

userdata/Manifest/gecko-1-b-win2012-gdt.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-1-b-win2016.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

@grenade As there is a delay to 8.3.0 rollout, let's go with 8.2.0 for now, which is already tested on the betas.

Upgrade all generic-worker installations to at least version 8.2.0

---

.taskcluster.yml
readme.md
userdata/Manifest/gecko-t-win10-64-gpu-b.json

The name `gecko-t-win10-64-gpu-beta` is too long so I was forced to shorten it to `gecko-t-win10-64-gpu-b`.
This is useful so screenshots will also work on gpu instances - at the moment we can't roll out 8.3.0 globally since older versions of mozharness don't respect `Content-Encoding` header of artifacts that the new 8.3.0 version of generic-worker produces. This has been fixed on mozilla-inbound / mozilla-central but it might take a while for try users to update their base revision, and I'm not sure if we have jobs running on other trees that might not have picked up this mozharness fix yet - so in order to unblock win10 testers, they can use this worker type, so long as they have an up-to-date mozharness.

Created worker type gecko-t-win10-64-gpu-b(eta)

---

.taskcluster.yml

See [bug description](https://bugzilla.mozilla.org/show_bug.cgi?id=1359003#c0) for context - essentially this retains artifacts for longer, to avoid that they expire before they are uploaded.

Bug 1359003 - retain CI http request and response artifacts for longer

---

userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json

@grenade This fixes the black screenshot issue ([bug 1343580](https://bugzilla.mozilla.org/show_bug.cgi?id=1343580)).

Upgrade all win10 worker types to use generic worker 8.3.0

---

userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-c.json

In addition to these changes, there are still some further steps we run on win7 but not on win10. @grenade Can you clarify if we need them?
1) Setting of `HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\2.7\\PythonPath` and `HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\2.7\\InstallPath` is done on win7, but not on win10.
2) We are running `c:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\ngen.exe executeQueuedItems` on win7, but not on win10.
If we need either of these, I can either add them to this PR, or create a separate one, as you wish.

Aligned win10 manifests some more with win7

---

userdata/Manifest/gecko-t-win10-64-gpu-c.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json

@grenade 
Just aligning the worker types, before we get rid of the "cu" ones (if we decide to do that).
I'll go and check worker type config now in the worker type definitions, to make sure they are also aligned.

win10 fixes

---

userdata/DynamicConfig.ps1
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012-gdt.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-1-b-win2016.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012.json

Filesystem indexing can hurt performance, interfere with various
processes (such as holding a handle on a file, preventing it from
being deleted), and offers no benefits to being enabled, at
least on the builders.
On testing machines, these statements are also likely true. However,
in some rare cases having indexing enabled may trigger conditions
that invalidate assumptions of tests, mainly that tests are running
on machines resembling what users run, which almost certainly have
indexing enabled. So this commit errors on the extreme side of
caution by not disabling indexing on test machines.

Bug 1362594 - Disable indexing on all volumes on builders

---

userdata/Manifest/gecko-t-win10-64-beta.json

When we run as task user, this is taken care of by generic worker, however when running as current user, generic worker can't influence the known folders, since they are determined when user profile is loaded, which is when generic worker user logs in (before generic worker process starts).
Fortunately, these known folders only need to be set once, after the generic worker user has been created. I created a tool for setting the known folder locations for an arbitrary user, and tested it on windows 10. It is working correctly.
There is one problem - we need to know the password of the generic worker account. Previously, we let generic worker program decide a password for us, randomly. I'm not sure best way to approach this. If we roll out to production, we'll need to decide a solution for …

Set known folders (LocalAppData, LocalAppDataLow, RoamingAppData)

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

This upgrades the beta worker types to use generic-worker 9.3.0 (which runs as a windows service, creates a user, and reboots into generated task user).

Upgrade beta worker types to use generic-worker 9.3.0

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Setting the `sha512` property implies that the binary is uploaded to tooltool. Once this becomes an accepted feature (i.e. we deploy to prod worker types, not betas), then I will make sure NSSM is published to tooltool (and check licence requirements etc).

Remove SHA512 sums for NSSM

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

This should fix the broken beta schemas.

ComponentName and ComponentType wrong way around for NSSM

---

.taskcluster.yml

Retries currently cause errors like:
```
An error occurred (InvalidAMIName.Duplicate) when calling the CreateImage operation: AMI name gecko-t-win7-32-cu version ce65a7230147 is already in use by AMI ami-6a335e0a
10:44 An error occurred (InvalidAMIName.Duplicate) when calling the CreateImage operation: AMI name gecko-t-win10-64-gpu-b version ce65a7230147 is already in use by AMI ami-160d6076
10:46 An error occurred (InvalidAMIName.Duplicate) when calling the CreateImage operation: AMI name gecko-t-win7-32-beta version ce65a7230147 is already in use by AMI ami-48325f28
```
This patch disables retries in the AMI generation tasks.
An alternative might be to check for an existing AMI and delete it first - but until then, this should be enough.

Don't retry AMI generation tasks in CI - causes error InvalidAMINameDuplicate

---

ci/update-workertype.sh
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-hw.json

In my try pushes, I had no issues with upgrading builders - so this is just rolling out the new worker on the 2012 builders.
Note:
1) There were a couple of entries in gecko-1-b-win2012 that weren't in gecko-2-b-win2012 and gecko-3-b-win2012 (LegacyHgShared, LegacyHgSharedAccessRights, MozillaCentralCacheCreate, MozillaCentralCacheUpdate) - I have added these to gecko-2-b-win2012 and gecko-3-b-win2012 for consistency. Let me know if these entries shouldn't be there.
2) I've made a small change (tested) to update-workertype.sh to update the config in the worker type definition, at the same time we update the AMI references and deploymentId. After this is merged, I propose we make a nodeploy commit and revert the change to update-workertype.sh (like I did in …

Upgrade all win2012 worker types to use generic worker 10.0.5

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

This fixes the issue whereby chain of trust artifacts were indexed in the chain of trust artifact by artifact path rather than artifact name.
Successfully [tested on try](https://treeherder.mozilla.org/#/jobs?repo=try&revision=c7bceb03cb6912502d50921406ca97b75ea5ab9b) using gecko-1-b-win2012-beta.
See [bug 1380978](https://bugzilla.mozilla.org/show_bug.cgi?id=1380978) for more details.
@grenade We can roll out in the morning when we're both around if you like - just wanted to get the PR out tonight.

Bug 1380978 - upgrade generic-worker to 10.1.6 on gecko-{1,2,3}-b-win2012

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

this change ensures that y:\hg-shared contains a prepopulated robustcheckout sharebase during ami creation and hopefully reduces checkout time on the first task checkout for each spot instance derived from that ami.

Bug 1381768 - precache for robustcheckout; r?pmoore

---

ci/update-workertype.sh
userdata/Configuration/GenericWorker/generic-worker.config

If worker type name ends with `-cu`, it implies runTasksAsCurrentUser should be `true`.
This is a bit of a hack, but it is a step closer to getting config managed automatically. In the end, we probably will want a python project or something similar that generates config automatically based on a set of rules, but for now, i put it in the `update-workertype.sh` script.
I discovered this issue because my `-cu` workertypes stopped working, which was my own fault!

Set runTasksAsCurrentUser based on worker type name

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-hw.json

Hey guys,
In bug 1382204 I'm rolling out coalescing/superseding which is a feature in the newest generic-worker. This patch upgrades the worker types which are on earlier versions of generic-worker 10. Workers still on an older version of generic-worker (8.2.0 / 8.3.0) will be upgraded in a separate bug, once tests have been greened up.
Here are the [try results](https://treeherder.mozilla.org/#/jobs?repo=try&revision=250ac5aa0061c27a848e0679e315ffbca1414d51&group_state=expanded&selectedJob=130034277&filter-tier=1) which show failures on win7 gpu/win7 non-gpu/win10 non-gpu, but I believe not for win10 gpu tasks, and not for win2012 tasks.
Thanks!
Pete

Bug 1382204 - upgrade generic-worker to 10.2.2 to enable coalescing

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

This upgrades mercurial on all the windows worker types to 4.3.1 from 3.9.1 that they were previously on.
Untested.

Bug 1390271 - Upgrade Mercurial 3.9.1 -> 4.3.1 on windows workers

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json

We can probably stop installing nsis-3.01 in the build machine now that MozillaBuild installs it, but I'd rather do that separately and test this first.

Update PATH following MozillaBuild update

---

userdata/Manifest/gecko-1-b-win2012-beta.json

Since NSIS 3.01 is already installed by MozillaBuild 3.1, there's no need to install it again.

Don't install NSIS 3.01, as it's already installed by MozillaBuild 3.1

---

userdata/Manifest/gecko-1-b-win2012.json

This is making `gecko-1-b-win2012` use MozillaBuild 3.1. Once we have deployed it, in a few days we can switch the test worker types to 3.1 too.

Bug 1413630 - Switch to MozillaBuild 3.1 in 64-bit build worker type

---

userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json

`NSSMDownload` was duplicated in `gecko-t-win10-64-gpu-b` (so could be removed) and also appeared in `gecko-t-win10-64-gpu` but is not needed as it runs `generic-worker 8.3.0` which isn't installed as a Windows service.

Removed NSSMDownload where it isn't needed

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat

Tested on gecko-t-win7-32-gpu-b (see bug for details).

Bug 1343049 - wait for user registry hive to be loaded before starting generic-worker

---

userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

This aligns `gecko-{2,3}-b-win2012` with `gecko-1-b-win2012`.

Upgraded level 2,3 workers to MozillaBuild 3.1

---

userdata/rundsc.ps1

See [Bug 1443595](https://bugzilla.mozilla.org/show_bug.cgi?id=1443595#c1) for context.

Bug 1443595 - use TLS 1.2 instead of TLS 1.0 when downloading files over HTTPS

---

userdata/Configuration/GenericWorker/generic-worker.config
userdata/rundsc.ps1
userdata/xDynamicConfig.ps1

Hey Rob,
Since [bug 1358545](https://bugzilla.mozilla.org/show_bug.cgi?id=1358545#c0) we now have startup checks that a signing key is present, and not readable by task users. This PR adds a chain of trust key generation for non-builders.
Note, the name of the feature "chain of trust" is mildly misleading here, since the feature is really "signed artifacts". It just so happens the primary use case of having signed artifacts is for chain of trust validation - but being able to sign artifacts for any task is a generally useful thing, as it provides some assurance that the artifact has not been tampered with, which is why it also useful to have on testers, even if we don't do chain-of-trust verification on test artifacts.
Thanks!
Pete

Signing key cot.key now required on all worker types, not just builders

---

userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

rather than rely on windows defender being disabled in the base ami, include a manifest component which explicitly disables it

Bug 1365909 - explicitly disable windows defender

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot-beta.bat
userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat

This will solve the issue, if we are sure [this line](https://github.com/mozilla-releng/OpenCloudConfig/blob/dbd82051b22f3cd336153d257f5509bf838652d0/userdata/rundsc.ps1#L1204) is run at the end of an OCC run. Rob, can you confirm if that is the case?
The problem was that `C:\dsc\task-claim-state.valid` file was being created before OCC has run, but since it is used to signal that generic worker can be started, it should only be created when OCC completes. Probably that is the case already, so we can just delete the creation in `run-generic-worker.bat`.
Note an alternative fix could be for the "Generic Worker" service not to auto start, but to be manually started when OCC has completed.

Don't create C:\dsc\task-claim-state.valid immediately before rebooting worker

---

userdata/Manifest/gecko-t-win10-64-hw.json

Part of Windows defender. Though Windows Defender was not scanning this process was running and consuming resources.

Bug 1456232 - disable antispyware executable

---

.taskcluster.yml
ci/rollback.py

- parse commit messages that contain rollback syntax in the format:
`rollback: worker-type git-sha`
eg:
`rollback: gecko-t-win7-32-beta 7480b11`
- query ec2 for amis associated with the specified worker type and git sha.
- query ec2 for security groups in the regions of the associated amis.
- update aws provisioner config for the specified worker type with the region specific ami ids and security groups resulting in an effective and immediate rollback
- when no rollback syntax is detected, create a list of available rollback configurations in the task log

Bug 1457416 - roll back ami deployments with commit syntax

---

userdata/Manifest/gecko-3-b-win2012.json

See [bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1465113#c4). Many thanks.

Bug 1465113 - Part 2: upgrade generic-worker on gecko-3-b-win2012 from 10.8.1 to 10.8.3

---

userdata/Configuration/ssh/sshd_config
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

modify sshd config implementing:
- disable password authentication (accept only ssh key authentication)
- log key fingerprint of successful connections
- other recommendations from https://infosec.mozilla.org/guidelines/openssh.html#intermediate-openssh-53

 Bug 1464343 - use hardened sshd config

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1465113](https://bugzil.la/1465113) for context.
Based on [the latest successful try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=990053bf529155a72efbdbb2ca4dabdee63d7871&group_state=expanded) this PR upgrades generic-worker to pick up latest bug fixes:
* [Bug 1466803 - Handle premature termination of livelog executable and log process output in task log](https://bugzil.la/1466803)
* [Bug 1465479 - Don't rely on a killed command returning immediately from Wait() call](https://bugzil.la/1465479)
* [Bug 1433854 - Clean up task users' home directories](https://bugzil.la/1433854)
* [Bug 1465112 - Move task reclaims into TaskStatusManager](https://bugzil.la/1465112)
* [Bug 1462369 - Kill entire process tree on Windows when aborting a task …

Bug 1465113 - Upgrade generic-worker from 10.8.1 to 10.8.4

---

userdata/Configuration/GenericWorker/run-hw-generic-worker-8-and-reboot.bat

After disk space less that 25 GB run a dism command. This command will clean up C:\Windows\WinSxS among other items. I putting this outside of the cleanup portion, so it will not run on every time generic worker exits. When this was the case we saw some odd behavior with this command.

Bug 1451837 - run dism command to clean up

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1468633](https://bugzil.la/1468633) for context.
This bugfix release includes the following generic-worker fixes:
generic-worker 10.8.5
* [Bug 1468631 - Close livelog channels when finished with them](https://bugzil.la/1468631)
* [Bug 1468155 - Check mounted artifact content's tasks are task dependencies](https://bugzil.la/1468155)
* [Bug 1466872 - Make sure zip file extraction doesn't allow extraction to paths starting ../](https://bugzil.la/1466872)
Tested in try push:
* https://treeherder.mozilla.org/#/jobs?repo=try&revision=c5c0f2b853e60a33c0b5b2e3822f086fe549eff5&group_state=expanded

Bug 1468633 - upgrade generic-worker from 10.8.4 to 10.8.5

---

userdata/Configuration/FirefoxBuildResources/robustcheckout.py

From changeset bfbbe0cc67be26f55b70a0ac4cffb86861879985 from
version-control-tools.
This will cause tasks to exit with code 72 if the repo is in a bad state
due to bug 1462323.

Bug 1469351 - Vendor latest robustcheckout

---

userdata/Configuration/Mercurial/mercurial.ini

this setting disables the hg thread pool for closing file handles which is a feature designed to optimise hg  when windows defender is running. in the case of our 2012 instances, defender is not installed and on win 7 and 10, defender is explicitly disabled. the setting should remove the overhead of this feature and make hg operations faster.

Bug 1474159 - disable hg thread pool for closing file handles

---

readme.md
userdata/Manifest/gecko-t-win10-64-hw-GW10.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/xDynamicConfig.ps1

- support is added here for replacing text in files with either a string or the output of a powershell expression.
- the win 10 hardware manifests are updated to use the text replacement component to match the log aggregator domain with the instance domain
- the instance domain is taken from the registry
- the "wintest.releng." prefix is removed, if present
- the string "mdc1.mozilla.com" in the nxlog config is replaced with the instance domain computed as described above

 Bug 1475764 - match log aggregator domain to instance domain 

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1480723](https://bugzil.la/1480723).
Here is a successful try push on staging with the new worker:
* https://treeherder.mozilla.org/#/jobs?repo=try&revision=18955f26cde6d7ef7cdf667ca0ccc24b2be92d69&group_state=expanded
This upgrade will roll out the following two new features:
* [Bug 1439588 - Add feature to support running Windows tasks in an elevated process (Administrator)](https://bugzil.la/1439588)
* [Bug 1469402 - Support for onExitStatus on generic-worker](https://bugzil.la/1469402)

Bug 1480723 - Upgrade generic-worker from 10.8.5 to 10.11.2 on Windows AWS worker types

---

userdata/Manifest/gecko-t-win7-32.json

Hi Rob, I need to check with @jmaher first if this is ok with him before we land it.
I wasn't sure which other worker types might have the performance tools also installed - do you know which step installs it, so I can see which other worker types also have it?
Thanks.

Bug 1439588 - make xperf.exe available in PATH on gecko-t-win7-32

---

ci/update-workertype.sh
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

this pr moves the instance type definitions into the worker type manifest.
instead of hard coding the instance type and block device mappings into the update-workertpe.sh ci script, we move those definitions into the json manifest which gives us support for multiple instance types within each worker type definition.

Bug 1480108 - support multiple instance types for each worker type

---

userdata/xDynamicConfig.ps1

if a sha512 was specified for tooltool download of a FileDownload component, validate the downloaded file has a sha512 hash matching the one in the manifest and use the result for the dsc validation of component run success

Bug 1480368 - validate sha512 hash on file download

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/rundsc.ps1

if a dsc run fails (indicated by the presence of "failed to execute Set-TargetResource" in the dsc transcript), this logic will cause occ to sleep until the taskcluster github task times out causing a deployment failure and preventing an incomplete ami from being deployed.

Bug 1480112 - handle dsc run failures

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw-GW10.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

this was deployed to beta workers earlier and tested here:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=d339170

Bug 1490703 - upgrade hg from 4.5.3 to 4.7.1

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw-GW10.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json

this pr updates the 64 bit production worker types with an updated mozilla build release
the 64 bit beta worker types were updated in earlier commits and tested here:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=983a809

Bug 1461340 upgrade mozilla build to v3.2

---

ci/validate.sh
ci/validate_json_syntax.sh
ci/validate_rsa_keys.sh
userdata/Configuration/ssh/readme.md

this pr adds a validation check on the contents of https://github.com/mozilla-releng/OpenCloudConfig/blob/master/userdata/Configuration/ssh/authorized_keys
specifically, it checks that all keys in this file have an rsa bit length of 2048 or higher.
if any key has an rsa bit length of less than 2048, the validation fails.

Bug 1493744 - validate ssh key rsa bit lengths

---

userdata/Configuration/nxlog/gecko-3-b-win2012.conf
userdata/Configuration/nxlog/hw-win10.conf
userdata/Configuration/nxlog/hw-win7.conf
userdata/Configuration/nxlog/win10.conf
userdata/Configuration/nxlog/win2012.conf
userdata/Configuration/nxlog/win7.conf
userdata/MaintainSystem.ps1
userdata/rundsc.ps1

this pr creates a new scheduled task called MaintainSystem which runs each minute on both hardware and ec2 workers. the task runs a new script called MaintainSystem.ps1 which currently has a single maintenance function which looks for task folders in the usual locations
- C:\Users\task_*
- Z:\task_*
if any task folders are found, all except the most recently created task folder are deleted by
- first taking ownership of the task folder and files and folders within it
- then adding an acl giving the adminitrators group full access to the task folder path and files and folders within it
- and finally deleting the task folder path and files and folders within it
additionally log events created by the scheduled task are forwarded to papertrail for debugging purposes

Maintain system

---

userdata/xDynamicConfig.ps1

use a unique filename for different versions of the same installer
- for msi installers, use the product id which is always unique for the version
- for exe & zip installers use the sha 512 hash if available

Bug 1495035 - distinguish installer versions

---

userdata/Configuration/GenericWorker/run-generic-worker-and-reboot.bat
userdata/HaltOnIdle.ps1
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/rundsc.ps1

this pr removes drive formatting of the z: drive between generic worker task runs.
this is done in preparation for reducing the number of volumes since we don't want to format drives containing caches or other required data.
also in the gw wrapper script there were some lines relating to a deprecated loaner mechanism that have been redundant for some time and do nothing. i've removed them to help reduce the unnecessary complexity of this script.

Bug 1479889 - remove drive format between tasks

---

userdata/rundsc.ps1

From 60 to 180 seconds. Some hardware nodes were getting into a state where winrm was timing out before rundsc.ps1 was finishing.

Bug 1499801 - Increase winrm timeout ... 

---

readme.md
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64-ux.json
userdata/Manifest/gecko-t-win10-64.json
userdata/OCC-Bootstrap.psm1
userdata/xDynamicConfig.ps1

Updates to Windows 10 have changed ACL permissions and ownership of the registry keys which govern access to Windows service settings for services which support the running of Windows Defender:
- HKLM:\SYSTEM\CurrentControlSet\Services\WdBoot
- HKLM:\SYSTEM\CurrentControlSet\Services\WdFilter
- HKLM:\SYSTEM\CurrentControlSet\Services\WdNisDrv
- HKLM:\SYSTEM\CurrentControlSet\Services\WdNisSvc
- HKLM:\SYSTEM\CurrentControlSet\Services\WinDefend
- HKLM:\SYSTEM\CurrentControlSet\Services\wscsvc
- HKLM:\SYSTEM\CurrentControlSet\Services\SecurityHealthService
- HKLM:\SYSTEM\CurrentControlSet\Services\Sense
This prevents stopping or changing the service startup type for Windows services: WdBoot, WdFilter, WdNisDrv, WdNisSvc, WinDefend, SecurityHealthService & Sense using the normal Windows …

 Bug 1509722 - disable windows defender & supporting services

---

userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64-ux.json
userdata/Manifest/gecko-t-win10-64.json

this change sets a number of registry keys relating to windows update configuration. additionally, it synchronises a couple prod/beta manifests which had slightly diverged:
- gecko-t-win10-64 is synced with gecko-t-win10-64-beta 
- gecko-t-win10-64-gpu is synced with gecko-t-win10-64-gpu-b
the sync changes are just to keep beta and prod manifests the same, so that change tests on beta are valid when promoted to prod.
one of the sync changes is to remove the nvidia 520 driver from prod where we recently upgraded the base ami to use g3 instances which use a different nvidia driver. the 520 driver was used to support g2 instances whch are no longer used. on g3 we bake the nvidia grid driver into the ami during iso-to-ami conversion (see: …

Bug 1485628 - disable service pack updates & reboots

---

cfg/datacenter-workertype-override-map.json
userdata/Manifest/gecko-t-win10-64-hw-b.json
userdata/Manifest/gecko-t-win10-64-ux-b.json
userdata/OCC-Bootstrap.psm1
userdata/rundsc.ps1
userdata/xDynamicConfig.ps1

this pr creates support for assigning hardware (moonshot) worker instances to alternative worker type definitions by creating an override map which is checked during occ initialisation.
the default worker type is determined by the hostname:
- t-w1064-hw-* is mapped by default to gecko-t-win10-64-hw
- t-w1064-ux-* is mapped by default to gecko-t-win10-64-ux
if an alternative worker type is defined for the hostname in cfg/datacenter-workertype-override-map.json then that worker type and its associated occ manifest will be applied at the first reboot after the mapping is pushed to the occ repo master branch.
registry based ci overrides of the worker type or source values can be disabled for an individual system by setting the following registry keys (manually):
- …

Bug 1512090 - set worker type for hardware on occ init

---

userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win7-32-cu.json

Hey Rob,
This patches the `*-cu` manifests to be consistent with their non `-cu` counterparts.
Thanks!

Align gecko-t-win{7-32,10-64}-cu manifests with gecko-t-win{7-32,10-64} manifests

---

userdata/Configuration/FirefoxBuildResources/robustcheckout.py

Recent versions of `robustcheckout` include new metrics output
and compatibility with newer versions of Mercurial. This commit
vendors the latest robustcheckout from version-control-tools,
revision 8e3bb142dfa9.

Bug 1535011: vendor latest `robustcheckout` from version-control-tools

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-c4.json
userdata/Manifest/gecko-3-b-win2012-c5.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-alpha.json
userdata/Manifest/gecko-t-win10-64-gpu-a.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/relops-image-builder.json

Reverts mozilla-releng/OpenCloudConfig#234, which itself reverted #233 - in other words, this PR is a second attempt to land #233 ([bug 1534983](https://bugzil.la/1534983)).
Initially #233 was reverted due to [bug 1543353](https://bugzil.la/1543353) - however the root cause was later discovered to be [bug 1543490](https://bugzil.la/1543490) which resulted in #235 which has since landed. Therefore it should be safe to land #233 again.

Revert "Revert "Bug 1534983 - Upgrade to generic-worker 14.0.2""

---

ci/papertrail-setup.sh
userdata/Configuration/nxlog/gecko-3-b-win2012.conf
userdata/Configuration/nxlog/hw-win10.conf
userdata/Configuration/nxlog/win10.conf
userdata/Configuration/nxlog/win10arm64.conf
userdata/Configuration/nxlog/win2012.conf
userdata/Configuration/nxlog/win2016.conf
userdata/Configuration/nxlog/win7.conf

i've created a new log destination in the papertrail "Mozilla Corporation" (releng) account and i have run the setup script included in this patch (it creates worker type specific pt groups matching those that exist in the treeherder account.

Bug 1543227 - send logs to mc papertrail (rather than th)

---

userdata/Configuration/GenericWorker/generic-worker.config
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-c4.json
userdata/Manifest/gecko-3-b-win2012-c5.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-alpha.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-a.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw-b.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64-ux-b.json
userdata/Manifest/gecko-t-win10-64-ux.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win10-a64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/relops-image-builder.json

In this condition, incoming access on the livelog GET port (60023,
mistakenly labeled as livelog PUT in the firewall rules) no longer
requires inbound access.  The PUT port never required inbound access --
it is only used on localhost.

Bug 1547966 - configure to use websocktunnel

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

This upgrades generic-worker to version 15.0.1 on the following worker types:
* gecko-1-b-win2012
* gecko-2-b-win2012
* gecko-3-b-win2012
* gecko-t-win7-32
* gecko-t-win7-32-gpu
* gecko-t-win10-64
* gecko-t-win10-64-gpu
See [bug 1559157](https://bugzil.la/1559157) for context.
Successful try push: [d569f9eb34a6c4abbda6801d083796203eab0b5b](https://treeherder.mozilla.org/#/jobs?repo=try&revision=d569f9eb34a6c4abbda6801d083796203eab0b5b&group_state=expanded).

Bug 1559157 - upgrade generic-worker to 15.1.0 

---

userdata/Manifest/gecko-t-win10-a64-beta.json

Bitbar is currently troubleshooting 1563662, and one of the steps being undertaken is to upgrade generic-worker.

Bug 1564603 - update generic-worker install target to 15.1.0 for windows10-aarch64

---

userdata/Manifest/gecko-t-win10-a64-beta.json

Apologies for the flurry of PRs.
generic-worker 15.1.0 seems to have some issues on windows10-aarch64 hardware and I was able to reproduce the issues. For the time being, 14.1.2 should be used as it does not experience the error that 15.1.0 did.

Bug 1564603 - downgrade version of generic-worker used to 14.1.2 due to issues with 15.1.0

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

Commit made with:
./gecko-try.sh -p -b gw-15.1.1 15.1.1 5.1.0
See https://github.com/taskcluster/generic-worker/blob/6737dbf737dd0cc52a8593861046e4442795485b/mozilla-try-scripts/gecko-try.sh
Hey Rob,
Based on [this successful try push](https://treeherder.mozilla.org/#/jobs?repo=try&selectedJob=256213619&revision=772e7f099df88b45e2c2c29b9424fadeb1704171&group_state=expanded), we should be good to deploy generic-worker 15.1.1 to production. No urgency. Thanks!
In v15.1.1 since v15.1.0
========================
* [Bug 1382668 - generic-worker: document the env vars that the worker implicitly sets in the task commands it runs](https://bugzil.la/1382668)
* [Bug 1562964 - generic-worker: log HTTP response body when getting a bad HTTP response code from the queue when uploading …

Deploying generic-worker 15.1.1 / taskcluster-proxy 5.1.0 to PRODUCTION

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

This upgrades generic-worker to version 15.1.5.
See [bug 1566365](https://bugzil.la/1566365) for more details.

Bug 1566365: deploy generic-worker 15.1.5

---

.taskcluster.yml

For example, if a worker panics/crashes during a task or there is a spot termination, a new task run should get automatically scheduled.

Enable task reruns in case of worker exceptions

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012-xlarge.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-c4.json
userdata/Manifest/gecko-3-b-win2012-c5.json
userdata/Manifest/gecko-3-b-win2012.json

This will need to wait a bit to land, until the patch on [bug 1562686](https://bugzilla.mozilla.org/show_bug.cgi?id=1562686) has merged around.  It's my understanding that sccache is not used for release builds, so we won't need this on release or ESR branches.

Bug 1562686 - stop providing IamInstanceProfile as it is unnecesary

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1536780](https://bugzil.la/1536780) for details.
Commit made with:
[gecko-try.sh](https://github.com/taskcluster/generic-worker/blob/165a50ac13ef09b6b2de65905c3aee82bd09bf5b/mozilla-try-scripts/gecko-try.sh) -p -b bug1536780 16.2.0 5.1.0
* [Successful try push](https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=3f8e233f8ad8b018f51c6a1d78d0f8b73a9c5c09)
* [Release notes](https://github.com/taskcluster/generic-worker#release-notes)

Bug 1536780 - deploy generic-worker 16.2.0 to *PRODUCTION*

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1588834](https://bugzil.la/1588834) for context.
Successful try push [here](https://treeherder.mozilla.org/#/jobs?repo=try&revision=005a0149b0fd86129434292d7be5153048af2e05&group_state=expanded).
Commit made with:
./gecko-try.sh -p -b bug1588834 16.4.0 5.1.0
See https://github.com/taskcluster/generic-worker/blob/v16.4.0/mozilla-try-scripts/gecko-try.sh

Deploy generic-worker 16.4.0 to production

---

userdata/Manifest/gecko-1-b-win2012-xlarge.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu-s.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/mpd001-1-b-win2012.json
userdata/Manifest/mpd001-3-b-win2012.json

This change updates worker types:
gecko-1-b-win2012-xlarge gecko-1-b-win2012 gecko-2-b-win2012 gecko-3-b-win2012 gecko-t-win10-64-gpu-s gecko-t-win10-64-gpu gecko-t-win10-64 gecko-t-win7-32-gpu gecko-t-win7-32 mpd001-1-b-win2012 mpd001-3-b-win2012
Commit made with:
./push-to-occ.sh -p -b bug1591769 16.5.1 5.1.0
See https://github.com/taskcluster/generic-worker/blob/48d34c3e0d4f0360c965fad5365659273d423e93/mozilla-try-scripts/push-to-occ.sh
Note, try push is [here](https://treeherder.mozilla.org/#/jobs?repo=try&revision=9f0a35a52d9321513a9a7b2515fcc39e08070629&group_state=expanded). The commit message is misleading, since it says it tests 16.5.0, but since 16.5.0 didn't start up, the tasks actually ran once 16.5.1 was deployed, so it is testing 16.5.1 after all. This can be verified by …

Upgrade to generic-worker 16.5.1 / taskcluster-proxy 5.1.0.

---

userdata/Configuration/GenericWorker/run-hw-generic-worker-10-and-reboot.bat
userdata/OCC-Bootstrap.psm1

This isn't ideal but will prevent the firewall notification on Yogas. Which is currently breaking tests. 
Rob, could you test this on your Yoga? For some reason I have never been able to get OCC to run on mine.

Bug 1405083 - Supress firewall notifications
