mozilla-releng/OpenCloudConfig

userdata/rundsc.ps1

the ephemeral drive names are significant because they are used as the build and user folders by the generic worker and may be referenced in code. this change detects drive letters of D: and E: and remaps them to Y: and Z: respectively.

sync win7 drive letter names with win2012 defaults

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/win10.json
userdata/Manifest/win2012.json
userdata/Manifest/win7.json

@grenade This includes fixes / features for e.g. bug 1313622 / bug 1298010.

Upgraded generic worker on all worker types to 6.1.0

---

userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

@grenade If this doesn't work, I quit! 😝

Upgrade generic worker to version 7.1.0 on all Windows test worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Upgraded generic worker from 7.1.2 to 7.1.3 on beta worker types

---

userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

Upgrade win7 and win10 worker types to generic worker 7.1.3

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

Upgraded win2012 worker types to generic worker 7.1.3

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Upgraded generic worker from 7.1.3 to 7.2.0 on beta worker types

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat
userdata/Manifest/gecko-t-win7-32-beta.json

Formats Z: drive after running generic worker, and then reboots

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat

Bug 1323990 - fix shutdown commands in run-generic-worker-format-and-reboot.bat

---

userdata/DynamicConfig.ps1
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win7-32-hw.json

determine worker type by operating system
- Windows 7: gecko-t-win7-32-hw
- Windows 10: gecko-t-win10-64-hw

support hardware worker type manifests

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Bug 1336948 - Upgrade generic-worker to 8.0.0 on beta worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

@grenade: This shouldn't cause any problems, but I'll keep an eye out and can roll back in case of problems.

Bug 1330569 - align on livelog 1.1.0

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

Bug 1336948 - Upgrade generic-worker to 8.0.0 on non-beta worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

Upgrade generic worker betas from 8.0.0 -> 8.0.1

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

Bug 1337132 - Upgrade to generic-worker v8.0.1

---

userdata/Manifest/gecko-t-win10-64-beta.json

Fix setting of RoamingAppData known folder location on gecko-b-win10-64-beta

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

I'm not entirely sure this will work - but if nobody else is using beta worker types at the moment, it shouldn't do any harm.
I've tested most of the changes that are in here, but not all - but I thought if I land it anyway, then I won't lose time if my other testing shows no problems.

Testing generic worker 9.1.1 on beta worker types

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-3-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win7-32-beta.json

The inevitable happened! It didn't work - minor bug fix here

---

userdata/PrepLoaner.ps1

the old mechanism of waiting for live logs to be deleted no longer works, so this change queries the taskcluster api to check for task completion.

bug 1384752 - determine task completion with tc api

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json

requires a green light from @indygreg

Bug 1390310 - update hg on builders to v4.3.1

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

Fixed nxlog download url

---

userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64-hw.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32-hw.json
userdata/Manifest/gecko-t-win7-32.json

This should fix DeleteMozillaBuildMercurial which currently does not work.

Bug 1408332 - fix broken DeleteMozillaBuildMercurial manifest entry

---

userdata/Configuration/Mozilla Maintenance Service/mms.bat

Previous URL was broken - is this updated one the correct one?

Fixed url to support.mozilla.org for MMS

---

ci/update-workertype.sh

Previously, we hardcoded which regions were configured for which worker types.
The problem with this was that sometimes we would e.g. manually disable or
enable a region in a worker type definition, and not realise OpenCloudConfig
would not update it automatically. This led to inconsistencies, such as this
one:
```
[taskcluster 2017-12-04T18:53:35.684Z] Worker Type (gecko-t-win10-64-gpu-b) settings:
[taskcluster 2017-12-04T18:53:35.684Z]   {
[taskcluster 2017-12-04T18:53:35.684Z]     "aws": {
[taskcluster 2017-12-04T18:53:35.684Z]       "ami-id": "ami-91c7eaf1",
[taskcluster 2017-12-04T18:53:35.684Z]       "availability-zone": "us-west-1b",
[taskcluster 2017-12-04T18:53:35.684Z]       "instance-id": "i-0e3371709fb7c605e",
[taskcluster 2017-12-04T18:53:35.684Z]       "instance-type": …
```

Copy AMIs to regions defined in worker type definition

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat
userdata/Configuration/GenericWorker/run-generic-worker.bat

... to see why OCC and GW are running at the same time.

More logging in run-generic-worker.bat 

---

userdata/Configuration/GenericWorker/run-generic-worker-format-and-reboot.bat
userdata/Configuration/fakemon.vbs
userdata/Configuration/nxlog/win10-grenade-elk-debug.conf
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/rundsc.ps1

We appear to not be running any tasks on AMIs generated from these changes. Let's back them out to restore order.

Back out recent commits for likely causing worker bustage in production

---

userdata/rundsc.ps1

Bug 1437522 - Add some ACLs

---

userdata/rundsc.ps1

the dsc configuration (xDynamicConfig.ps1) is compiled to a .net application (.mof) for the dsc run. as such it doesn't use tls 1.2 by default on all versions of the .net framework. this patch attempts to set strong cryptography use as the default for all .net apps on the system.
see: https://www.johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications

Bug 1443595 - use strong crypto (tls 1.2) by default

---

userdata/Configuration/GenericWorker/generic-worker.config
userdata/Configuration/GenericWorker/task-user-init-win10.cmd
userdata/Configuration/GenericWorker/task-user-init-win2012.cmd
userdata/Configuration/GenericWorker/task-user-init-win7.cmd
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-cu.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-cu.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

Hey Rob,
This is the big scary change.
Thanks!
Pete

Bug 1399401 - upgrade workers to generic-worker 10.7.8

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json

See [bug 1465113](https://bugzil.la/1465113) for details.

Bug 1465113 - Upgrade generic-worker from 10.8.1 to 10.8.3 on Windows infra

---

userdata/Configuration/GenericWorker/task-user-init-win10.cmd

See [bug 1465363](https://bugzilla.mozilla.org/show_bug.cgi?id=1465363) for context.

Bug 1465363 - don't prompt when adding reg key

---

userdata/Configuration/GenericWorker/run-hw-generic-worker-10-and-reboot.bat
userdata/Manifest/gecko-t-win10-64-hw-GW10.json
userdata/rundsc.ps1
userdata/xDynamicConfig.ps1

OCC will look for a file to determine if the new Win hw manifest will be applied. 
This also introduces hw-DiskManage which will report on and clean the disk. 
Verbal R+ from Rob.

Bug 1443589 - Upgrade Win 10 hw to GenericWorker 10.8.5

---

userdata/xDynamicConfig.ps1

This reverts commit dd11979c6362886ae2d6c0fcf472abb0ec2b0f91.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1496526

Bug 1496526 - Revert "Bug 1495035 - distinguish installer versions"

---

userdata/rundsc.ps1

based on location from primary search domain. 
Also remove some ineffective code. The test for the github connection was placed before the locationtype variable was defined and there actually has not been any issue connecting to github. 
The onedrive bit is now being fully addressed in the deployment piece.

Bug 1501705 - Set NTP server for hardware.. 

---

userdata/MaintainSystem.ps1
userdata/rundsc.ps1

occ's rundsc.ps1 contains a fair amount of logic and decision trees that are not correctly logged in papertrail.
refactor the script so that all processing occurs inside of a function that includes appropriately verbose logging for the logic being processed.

Bug 1504971 - refactor rundsc into logged functions that include processing time metrics

---

ci/update-workertype.sh
modules/OpenCloudConfig/DynamicConfig.psm1
modules/OpenCloudConfig/OpenCloudConfig.psd1
userdata/Manifest/gecko-1-b-win2012-beta.json
userdata/Manifest/gecko-t-win10-64-beta.json
userdata/Manifest/gecko-t-win10-64-gpu-b.json
userdata/Manifest/gecko-t-win7-32-beta.json
userdata/Manifest/gecko-t-win7-32-gpu-b.json
userdata/OCC-Bootstrap.psm1

- update win 2012 and win 7 base amis with latest nxlog
- add timeout & check for running dirmngr service on gpg4win install validation
- remove redundant gw user credentials from secrets (used on gw before v10)

Bug 1524592 - occ prep for gw 13

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-c4.json
userdata/Manifest/gecko-3-b-win2012-c5.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-alpha.json
userdata/Manifest/gecko-t-win10-64-gpu-a.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/relops-image-builder.json

See [bug 1534983](https://bugzil.la/1534983) for details. Thanks!

Bug 1534983 - Upgrade to generic-worker 14.0.2

---

userdata/Manifest/gecko-1-b-win2012.json
userdata/Manifest/gecko-2-b-win2012.json
userdata/Manifest/gecko-3-b-win2012-c4.json
userdata/Manifest/gecko-3-b-win2012-c5.json
userdata/Manifest/gecko-3-b-win2012.json
userdata/Manifest/gecko-t-win10-64-alpha.json
userdata/Manifest/gecko-t-win10-64-gpu-a.json
userdata/Manifest/gecko-t-win10-64-gpu.json
userdata/Manifest/gecko-t-win10-64.json
userdata/Manifest/gecko-t-win7-32-gpu.json
userdata/Manifest/gecko-t-win7-32.json
userdata/Manifest/relops-image-builder.json

Reverts mozilla-releng/OpenCloudConfig#233 due to [bug 1543353](https://bugzil.la/1543353).

Revert "Bug 1534983 - Upgrade to generic-worker 14.0.2"

---

userdata/MaintainSystem.ps1

See [bug 1543490](https://bugzil.la/1543490) for details.
Thanks Rob!

Bug 1543490 - retain latest *two* generic-worker task directories

---

ci/update-workertype.sh

See [bug 1584923](https://bugzil.la/1584923) for context. Thanks!

Bug 1584923 - include $RUN_ID in EC2 run-instances --client-token parameter

---

ci/update-workertype.sh

Hey Rob,
It looks like the AMI name needs to be unique too, so we should include `${TASK_ID}/${RUN_ID}` in AMI name too.
See e.g. [this failure](https://tools.taskcluster.net/groups/YxEziyFtQ96XiFC75nGObQ/tasks/OU4zq_TCQNGkbWzwSkCKtA/runs/2/logs/public%2Flogs%2Flive.log#L110).
Thanks!
See [bug 1584923](https://bugzil.la/1584923) for context.

Bug 1584923 - Include taskId/runId in AMI name

---

userdata/Configuration/FirefoxBuildResources/robustcheckout.py

Updates the vendored copy of robustcheckout to the latest version,
taken from changeset 102106f53cb2 in version-control-tools.
This version includes compatibility with the latest Mercurials,
Py3 support and some new metrics data.

Bug 1607614 - update robustcheckout.py with latest version
